services:
  app:
    image: ajohnsson95/userserviceajch
    depends_on:
      - mysql
    ports:
      - 8087:8087
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userservicedatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PlATFORM: mysql
    restart: on-failure

  mysql:
    image: 'mysql:8.3.0'
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_DATABASE: userservicedatabase
    ports:
      - '3306:3306'