name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t ajohnsson95/userserviceajch:latest .

      - name: Push Docker Image
        run: docker push ajohnsson95/userserviceajch:latest

      - name: Start Docker Compose
        run: docker-compose up -d